scan_filter_chain:
- name: angle1
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: 2.1
    upper_angle: 3.2 
- name: angle2
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.2
    upper_angle: -2.1