# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#


#base_global_planner: keeping the  default: "navfn/NavfnROS"
base_global_planner: "navfn/NavfnROS"
#base_local_planner: keeping the default: "base_local_planner/TrajectoryPlannerROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

#controller_frequency default is 20
controller_frequency: 20.0 #6.0  

#conservative_reset_dist deafalut is 3.0
conservative_reset_dist : 2.0

#recovery_behavior_enabled default is true
recovery_behavior_enabled:  true

#clearing_rotation_allowed default is true
clearing_rotation_allowed : true
#shutdown_costmaps default false

#oscillation_timeout deafult is 0.0 (infinte timeout)
oscillation_timeout: 20.0

#oscillation_distance default 0.5
oscillation_distance: 0.5

# recovery_behaviors: [
#   {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
#   {name: rotate_recovery1, type: rotate_recovery/RotateRecovery},
#   {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
#   {name: rotate_recovery2, type: rotate_recovery/RotateRecovery}
# ]

# conservative_clear:
#   reset_distance: 3.0
# agressive_clear:
#   reset_distance: 1.875
# rotate_recovery1:
#   sim_granularity: 0.017
#   frequency: 20.0
# rotate_recovery2:
#   sim_granularity: 0.017
#   frequency: 20.0